### ISSUE TITLE
Create word entry form

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/v43-tier1-team-08#15]
Create html form with css including

- [ ] labels to describe top of word needed
- [ ] text input fields
- [ ] submit button
- [ ] reset button

**Comment by terrifricker** [comment]
The labels from my story are:
Creature
Adjective
Verb ending in  “ed”
Feeling
Type of Clothing
Something Sparkly
Superpower
Favorite Food
Favorite Game
Animal
Favorite Song
Room in House
Favorite Place to Go
Secret Password

**Comment by mmsaki** [comment]
hey @terrifricker @ss-deep I notice that this issue is also referencing some features with issue #14 referencing the text inputs which are part of the form creation. What would be the best way to resolve these two issues? My thoughts are issue #14 already has may tasks assigned and so this issue # #15 is safe and can continue work on the text inputs on the form.

For reference here's: the design:


![Image](https://user-images.githubusercontent.com/98189596/225773608-fc2b29d0-3c5b-4ad4-beab-70e226e8464c.png)

**Comment by terrifricker** [comment]
Exactly, @mmsaki .  This task was only for creating the form that would then be placed inside the landing page created from issue #14
